test-warnings: no
strictness: medium
python-targets:
    - 2.7
    - 3
ignore-paths:
    - conftrak/__init__.py
    - conftrak/_version.py
    - versioneer.py
pylint:
  disable:
    - protected-access
