language: python
sudo: false

services:
  - mongodb

python:
  - 3.4
  - 3.5

before_install:
  - git clone https://github.com/nsls-ii/nsls2-ci ~/scripts
  - . ~/scripts/install-miniconda.sh

install:
  - conda create -n testenv --yes nose python=$TRAVIS_PYTHON_VERSION pymongo ujson tornado jsonschema pyyaml pytz doct -c lightsource2
  - source activate testenv
  - pip install coveralls codecov mongoquery pytest pytest-cov requests
  - python setup.py develop

script:
  - nohup python startup.py --mongo_host localhost --mongo_port 27017 --timezon US/Eastern --database conftrak_test --service-port 7771 &
  - py.test -sv --cov=conftrak --cov-report term-missing
          
after_success:
  - coveralls
  - codecov
